// <auto-generated />
using System;
using Academia_De_Idiomas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academia_De_Idiomas.Migrations
{
    [DbContext(typeof(AplicacionDbContext))]
    partial class AplicacionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Academia_De_Idiomas.Models.Alumnos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ApeAlum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodIdiomaId")
                        .HasColumnType("int");

                    b.Property<int?>("CodModalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdProfeId")
                        .HasColumnType("int");

                    b.Property<string>("NomAlum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodIdiomaId");

                    b.HasIndex("CodModalidadId");

                    b.HasIndex("IdProfeId");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Academia_De_Idiomas.Models.Idiomas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NomIdioma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Idiomas");
                });

            modelBuilder.Entity("Academia_De_Idiomas.Models.Modalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NomModalidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modalidad");
                });

            modelBuilder.Entity("Academia_De_Idiomas.Models.Profesores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NomProfe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idIdiomaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idIdiomaId");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("Academia_De_Idiomas.Models.Alumnos", b =>
                {
                    b.HasOne("Academia_De_Idiomas.Models.Idiomas", "CodIdioma")
                        .WithMany()
                        .HasForeignKey("CodIdiomaId");

                    b.HasOne("Academia_De_Idiomas.Models.Modalidad", "CodModalidad")
                        .WithMany()
                        .HasForeignKey("CodModalidadId");

                    b.HasOne("Academia_De_Idiomas.Models.Profesores", "IdProfe")
                        .WithMany()
                        .HasForeignKey("IdProfeId");

                    b.Navigation("CodIdioma");

                    b.Navigation("CodModalidad");

                    b.Navigation("IdProfe");
                });

            modelBuilder.Entity("Academia_De_Idiomas.Models.Profesores", b =>
                {
                    b.HasOne("Academia_De_Idiomas.Models.Idiomas", "idIdioma")
                        .WithMany()
                        .HasForeignKey("idIdiomaId");

                    b.Navigation("idIdioma");
                });
#pragma warning restore 612, 618
        }
    }
}
